language: php

php:
  - 5.5
  - 5.6
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: 5.5
    - php: hhvm

before_script:
  - git submodule update --init
  - cd holiday_jp/; git fetch origin master; git reset --hard origin/master; cd ../
  - composer install

script: vendor/bin/phpunit
